// scripts/testSSO.js
// Test script for SSO integration

const jwt = require('jsonwebtoken');
const fs = require('fs');
const path = require('path');

// Sample test data
const testUser = {
  sub: 'test-user-123',
  email: 'test@company.com',
  name: 'Test User',
  role: 'employee',
  employee_id: 'EMP001',
  domain: 'company.com',
  iss: process.env.SSO_ISSUER || 'https://test-sso-portal.com',
  aud: process.env.SSO_AUDIENCE || 'it-management-portal',
  exp: Math.floor(Date.now() / 1000) + (8 * 60 * 60), // 8 hours from now
  iat: Math.floor(Date.now() / 1000)
};

// Generate a test JWT token (for testing purposes only)
// In production, this would be generated by your SSO portal
function generateTestToken() {
  // Use your JWT_SECRET for testing (in production, SSO portal would use its own private key)
  const secret = process.env.JWT_SECRET || 'test-secret-key';
  
  const token = jwt.sign(testUser, secret, { 
    algorithm: 'HS256', // Using HS256 for testing (matches the middleware)
    expiresIn: '8h'
  });
  
  return token;
}

// Generate test URL
function generateTestURL() {
  const token = generateTestToken();
  const baseURL = 'http://localhost:3000';
  const returnURL = '/dashboard';
  
  return `${baseURL}?sso_token=${token}&return_url=${returnURL}`;
}

// Main function
function main() {
  console.log('🔐 SSO Integration Test Script');
  console.log('================================');
  console.log('');
  
  console.log('Test User Data:');
  console.log(JSON.stringify(testUser, null, 2));
  console.log('');
  
  const testToken = generateTestToken();
  console.log('Generated Test Token:');
  console.log(testToken);
  console.log('');
  
  const testURL = generateTestURL();
  console.log('Test URL (copy and paste into browser):');
  console.log(testURL);
  console.log('');
  
  console.log('Instructions:');
  console.log('1. Make sure your backend server is running');
  console.log('2. Make sure your frontend server is running');
  console.log('3. Copy the test URL above and paste it into your browser');
  console.log('4. You should be automatically logged in and redirected to the dashboard');
  console.log('');
  
  console.log('Note: This is a test token for development only.');
  console.log('In production, tokens will be generated by your SSO portal.');
}

// Run the script
if (require.main === module) {
  main();
}

module.exports = {
  generateTestToken,
  generateTestURL,
  testUser
};
